---
version: 2.1
executors:
  toxandnode:
    working_directory: ~/project
    docker:
      - image: girder/tox-and-node
      - image: memcached
      - image: mongo:4.4
        command: bash -c "mkdir /dev/shm/mongo && mongod --nojournal --dbpath=/dev/shm/mongo --noauth --bind_ip_all"
      - image: rabbitmq
commands:
  tox:
    description: "Run tox"
    parameters:
      env:
        type: string
    steps:
      - run:
          name: Preinstall phantomjs to work around an npm permission issue
          command: npm install -g phantomjs-prebuilt --unsafe-perm
      - run:
          name: Run tests via tox
          # Piping through cat does less buffering of the output but can
          # consume the exit code
          command: PYTEST_NUMPROCESSES=2 tox -e << parameters.env >> | cat; test ${PIPESTATUS[0]} -eq 0

jobs:
  test:
    executor: toxandnode
    steps:
      - checkout
      - tox:
          env: test

workflows:
  version: 2
  ci:
    jobs:
      - test
  periodic:
    triggers:
      - schedule:
          cron: "0 0 * * 3"
          filters:
            branches:
              only:
                - main
    jobs:
      - test
